project_name: reflow

before:
  hooks:
    - go mod tidy

builds:
  - id: reflow-cli
    main: ./main.go
    binary: reflow
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X reflow/cmd/version.version={{.Version}}
      - -X reflow/cmd/version.repository=RevereInc/reflow
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: reflow-archives
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  name_template: "Release {{.Version}}"